### ISSUE TITLE
Question on: summary.tax

### ISSUE THREAD

**Issue by dwilliamthompson** [mothur/mothur.github.io#53]
I followed this line by line and this is my output for the Group section: 
"mothur > summary.tax(taxonomy=stool.trim.unique.good.filter.unique.precluster.pick.rdp.taxonomy, name=stool.trim.unique.good.filter.unique.precluster.pick.names, group=stool.good.pick.groups)

It took 0 secs to create the summary file for 27517 sequences.

Output File Names:
C:\Users\Grose lab\Desktop\Kentucky_1\stool.trim.unique.good.filter.unique.precluster.pick.rdp.tax.summary"

My issue is when I type the next line: 
mothur > summary.tax(taxonomy=stool.trim.unique.good.filter.unique.precluster.pick.rdp.taxonomy, name=stool.trim.unique.good.filter.unique.precluster.pick.names, group=stool.good.pick.groups)

It took 0 secs to create the summary file for 27517 sequences.

Output File Names:
C:\Users\Grose lab\Desktop\Kentucky_1\stool.trim.unique.good.filter.unique.precluster.pick.rdp.tax.summary

mothur > summary.tax(taxonomy=stool.trim.unique.good.filter.unique.precluster.pick.rdp.taxonomy, count=stool.trim.unique.good.filter.unique.precluster.pick.count_table)

Unable to open C:\Users\Grose lab\Desktop\Kentucky_1\stool.trim.unique.good.filter.unique.precluster.pick.count_table. Trying input directory C:\Users\Grose lab\Desktop\Kentucky_1\stool.trim.unique.good.filter.unique.precluster.pick.count_table.
Unable to open C:\Users\Grose lab\Desktop\Kentucky_1\stool.trim.unique.good.filter.unique.precluster.pick.count_table. Trying default C:\Users\Grose lab\Desktop\Mothur.win\mothur\stool.trim.unique.good.filter.unique.precluster.pick.count_table.
Unable to open C:\Users\Grose lab\Desktop\Mothur.win\mothur\stool.trim.unique.good.filter.unique.precluster.pick.count_table. Trying mothur's executable location C:\Users\Grose lab\Desktop\Mothur.win\mothur\stool.trim.unique.good.filter.unique.precluster.pick.count_table.
Unable to open C:\Users\Grose lab\Desktop\Mothur.win\mothur\stool.trim.unique.good.filter.unique.precluster.pick.count_table. Trying mothur's tools location stool.trim.unique.good.filter.unique.precluster.pick.count_table.
Unable to open stool.trim.unique.good.filter.unique.precluster.pick.count_table.
Unable to open C:\Users\Grose lab\Desktop\Kentucky_1\stool.trim.unique.good.filter.unique.precluster.pick.count_table
[ERROR]: did not complete summary.tax.

What did I do wrong?

**Comment by mothur-westcott** [comment]
The count file is a condensed version of the name / group files. Using the count file instead of the name / group file is recommended, because it reducing processing time and memory usage. Did you run the make.table command to create the count file?

mothur > make.table(name=stool.trim.unique.good.filter.unique.precluster.pick.names, group=stool.good.pick.groups) - create count file from name / group files

mothur > summary.tax(taxonomy=stool.trim.unique.good.filter.unique.precluster.pick.rdp.taxonomy, count=current) - summarize taxonomy results using count file

Another thing to consider, https://mothur.org/wiki/frequently_asked_questions/#mothur-cant-find-my-input-files.
