### ISSUE TITLE
Question on creating corresponding shared and taxonomy files

### ISSUE THREAD

**Issue by MohammadHKhan** [mothur/mothur.github.io#73]
After MiSEQ, I got a shared and taxonomy file. But, our group decided to exclude some of the samples for the analysis.
So, I used remove.groups command to remove some of the samples from the shared file. 
But now, the taxonomy file (consist of OTU, Size and Taxonomy) doesn't corresponds to the shared file. This is obviously because some of the OTUS were removed with samples while using remove.groups command on shared file.

So, how to remove OTUS in taxonomy file that corresponded with the removed groups of the shared file and create a taxonomy file that correspond to my updated shared file?
I hope I clearly discussed my issue.

**Comment by mothur-westcott** [comment]
The consensus taxonomies will need to be recalculated since they were created using sequences from the groups you want to remove. Consider the following trivial example:

OTU001 -> seq1,seq2,seq3,seq4,seq5

seq1,seq3,seq5 are from a sample named odd, and classify to Bacteria(100);Firmicutes(100);Bacilli(100);Lactobacillales(100);Lactobacillaceae(100);Lactobacillus(100);

seq2,seq4 are from a sample named even, and classify to Bacteria(100);Firmicutes(100);Clostridia(100);Clostridiales(100);Ruminococcaceae(100);Oscillibacter(100);

The consensus taxonomy for OTU1 with both samples would look like: Bacteria(100);Firmicutes(100);Firmicutes_unclassified(100);Firmicutes_unclassified(100);Firmicutes_unclassified(100);Firmicutes_unclassified(100);

The consensus taxonomy for OTU1 with only the even sample would look like: Bacteria(100);Firmicutes(100);Clostridia(100);Clostridiales(100);Ruminococcaceae(100);Oscillibacter(100);


Try this:

mothur > remove.groups(fasta=yourFastaFile, count=yourCountFile, taxonomy=yourTaxonomyFile, groups=groupsToRemove) - remove unwanted samples from analysis

mothur > cluster.split(fasta=current, taxonomy=current, count=current) - create OTUs with sample you want to include

mothur > make.shared(list=current, count=current) - create shared file

mothur > classify.otu(list=current, taxonomy=current, count=current) - create consensus taxonomies

**Comment by MohammadHKhan** [comment]
Thanks Sarah. That helped a lot.
